$ErrorActionPreference = "Stop"

Set-Location (Join-Path $PSScriptRoot "..")

Write-Host "[setup-local-db] Starting MySQL container..."
docker compose up -d | Out-Null

$containerId = docker compose ps -q db-smart-manekin-2026
if (-not $containerId) {
  throw "MySQL container is not running. Please check docker compose output."
}

Write-Host "[setup-local-db] Applying schema to dbsensor..."

$schema = @"
CREATE DATABASE IF NOT EXISTS dbsensor;
USE dbsensor;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY users_email_unique (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mannequin (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO mannequin (id, name) VALUES (1, 'Default Mannequin');

CREATE TABLE IF NOT EXISTS sensor_types (
  sensor_type_id BIGINT UNSIGNED NOT NULL,
  sensor_type VARCHAR(255) NOT NULL,
  PRIMARY KEY (sensor_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sensors (
  sensor_id BIGINT UNSIGNED NOT NULL,
  sensor_name VARCHAR(255) NOT NULL,
  sensor_type_id BIGINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (sensor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO sensor_types (sensor_type_id, sensor_type) VALUES
(1, 'MQ'), (2, 'ADXL'), (3, 'MPU'), (6, 'KY'), (7, 'THERMAL/DHT'), (8, 'LOADCELL'), (9, 'LIDAR'), (10, 'BME/WIT'), (11, 'SKIN');

INSERT IGNORE INTO sensors (sensor_id, sensor_name, sensor_type_id) VALUES
(101, 'MQ-101', 1), (102, 'MQ-102', 1), (103, 'MQ-103', 1),
(201, 'ADXL tangan kanan', 2), (202, 'ADXL tangan kiri', 2), (203, 'ADXL kaki kanan', 2), (204, 'ADXL kaki kiri', 2),
(601, 'KY kanan', 6), (602, 'KY kiri', 6),
(701, 'DHT11', 7), (702, 'Thermal Camera', 7),
(801, 'Loadcell 1', 8), (802, 'Loadcell 2', 8), (803, 'Loadcell 3', 8), (804, 'Loadcell 4', 8), (805, 'Loadcell 5', 8), (806, 'Loadcell 6', 8),
(901, 'Lidar', 9), (902, 'Lidar Test', 9),
(1001, 'BME280', 10), (1002, 'MPU6050', 10), (1010, 'Witsensor', 10),
(1101, 'rp_tangan_kiri', 11), (1102, 'rp_tangan_kanan', 11), (1103, 'flex_tangan_kiri', 11), (1104, 'flex_tangan_kanan', 11),
(1105, 'rp_kaki_kiri', 11), (1106, 'rp_kaki_kanan', 11), (1107, 'flex_kaki_kiri', 11), (1108, 'flex_kaki_kanan', 11);

CREATE TABLE IF NOT EXISTS mq2 (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,3) NOT NULL DEFAULT 0,
  co DECIMAL(10,3) NOT NULL DEFAULT 0,
  co2 DECIMAL(10,3) NOT NULL DEFAULT 0,
  nh3 DECIMAL(10,3) NOT NULL DEFAULT 0,
  no2 DECIMAL(10,3) NOT NULL DEFAULT 0,
  smoke DECIMAL(10,3) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ky_kanan (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ky_kiri (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS adxl_tangan_kanan (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  x_axis DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_axis DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_axis DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_kalman DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_kalman DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_kalman DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS adxl_tangan_kiri LIKE adxl_tangan_kanan;
CREATE TABLE IF NOT EXISTS adxl_kaki_kanan LIKE adxl_tangan_kanan;
CREATE TABLE IF NOT EXISTS adxl_kaki_kiri LIKE adxl_tangan_kanan;

CREATE TABLE IF NOT EXISTS bme280 (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  temperature DECIMAL(10,2) NOT NULL DEFAULT 0,
  pressure DECIMAL(10,2) NOT NULL DEFAULT 0,
  approximate_altitude DECIMAL(10,2) NOT NULL DEFAULT 0,
  humidity DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dht11 (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  temperature DECIMAL(10,3) NOT NULL DEFAULT 0,
  humidity DECIMAL(10,3) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lidar (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  kalmanvalue DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lidartest (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mpu6050 (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  temperature DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_kalman DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_kalman DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_kalman DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_rotation DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_rotation DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_rotation DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS thermal_camera (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  low_temp DECIMAL(10,2) NOT NULL DEFAULT 0,
  center_temp DECIMAL(10,2) NOT NULL DEFAULT 0,
  high_temp DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS witsensor (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  x_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  a_acceleration DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_velocity DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_velocity DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_velocity DECIMAL(10,2) NOT NULL DEFAULT 0,
  w_velocity DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_angle DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_angle DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_angle DECIMAL(10,2) NOT NULL DEFAULT 0,
  x_magnetic DECIMAL(10,2) NOT NULL DEFAULT 0,
  y_magnetic DECIMAL(10,2) NOT NULL DEFAULT 0,
  z_magnetic DECIMAL(10,2) NOT NULL DEFAULT 0,
  h_magnetic DECIMAL(10,2) NOT NULL DEFAULT 0,
  pressure DECIMAL(10,2) NOT NULL DEFAULT 0,
  height DECIMAL(10,2) NOT NULL DEFAULT 0,
  q0_quaternion DECIMAL(10,2) NOT NULL DEFAULT 0,
  q1_quaternion DECIMAL(10,2) NOT NULL DEFAULT 0,
  q2_quaternion DECIMAL(10,2) NOT NULL DEFAULT 0,
  q3_quaternion DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS loadcell_1 (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  kalmanvalue DECIMAL(10,2) NOT NULL DEFAULT 0,
  lateral_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  extension_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  flexion_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS loadcell_2 LIKE loadcell_1;
CREATE TABLE IF NOT EXISTS loadcell_3 LIKE loadcell_1;
CREATE TABLE IF NOT EXISTS loadcell_4 LIKE loadcell_1;
CREATE TABLE IF NOT EXISTS loadcell_5 LIKE loadcell_1;
CREATE TABLE IF NOT EXISTS loadcell_6 LIKE loadcell_1;

CREATE TABLE IF NOT EXISTS rp_tangan_kiri (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  pressure_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  force_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rp_tangan_kanan LIKE rp_tangan_kiri;
CREATE TABLE IF NOT EXISTS flex_tangan_kiri LIKE rp_tangan_kiri;
CREATE TABLE IF NOT EXISTS flex_tangan_kanan LIKE rp_tangan_kiri;
CREATE TABLE IF NOT EXISTS rp_kaki_kiri LIKE rp_tangan_kiri;
CREATE TABLE IF NOT EXISTS rp_kaki_kanan LIKE rp_tangan_kiri;
CREATE TABLE IF NOT EXISTS flex_kaki_kiri LIKE rp_tangan_kiri;
CREATE TABLE IF NOT EXISTS flex_kaki_kanan LIKE rp_tangan_kiri;

CREATE TABLE IF NOT EXISTS skin (
  event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  inputed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  sensor_id BIGINT UNSIGNED NOT NULL,
  mannequin_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  fsr1 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr2 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr3 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr4 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr5 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr6 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr7 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr8 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr9 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr10 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr11 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr12 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr13 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr14 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr15 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr16 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr17 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr18 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr19 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr20 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr21 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr22 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr23 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr24 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr25 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr26 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr27 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr28 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr29 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr30 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr31 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr32 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr33 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr34 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr35 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr36 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr37 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr38 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr39 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr40 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr41 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr42 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr43 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr44 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr45 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr46 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr47 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr48 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr49 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr50 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr51 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr52 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr53 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr54 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr55 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr56 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr57 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr58 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr59 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr60 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr61 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr62 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr63 DECIMAL(10,2) NOT NULL DEFAULT 0,
  fsr64 DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"@

$schema | docker exec -i $containerId mysql -uroot -proot dbsensor

Write-Host "[setup-local-db] Done."
Write-Host "[setup-local-db] Run backend with: pnpm start"
